version: "3.9"
services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8080"
    volumes:
      - ./backend:/app  
    env_file:
      - ./backend/.env     
    environment:
      - PYTHONUNBUFFERED=1
    command: uvicorn app.api.main:app --host 0.0.0.0 --port 8080 --reload

  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
